services:
  backend:
    build:
      context: backend
      target: development
    ports:
      - 80:80
      - 9229:9229
      - 9230:9230
networks:
  public:
  private:
volumes:
  back-notused:
  db-data:
secrets:
  db-password:
    file: db/password.txt
